bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind P source-file -F "#{@dirPrograms}/project-search.tmux.conf";
bind N source-file -F "#{@dirPrograms}/project-create.tmux.conf";
bind O source-file -F "#{@dirPrograms}/context-prompt.tmux.conf";
bind o source-file -F "#{@dirPrograms}/context-prompt-ref.tmux.conf";
bind F source-file -F "#{@dirPrograms}/context-query.tmux.conf";
bind H source-file -F "#{@dirPrograms}/ssh.tmux.conf";
bind X source-file -F "#{@dirPrograms}/debug-menu.tmux.conf";

bind-key -T copy-mode-vi E send-keys -X copy-pipe-and-cancel "cat > /tmp/ttmux-edit-selection && tmux split-window -h 'nvim /tmp/ttmux-edit-selection'"
