bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind P source-file -F "#{@dirPrograms}/project-search.tmux.conf";
bind N source-file -F "#{@dirPrograms}/project-create.tmux.conf";
bind O source-file -F "#{@dirPrograms}/context-prompt.tmux.conf";
bind F source-file -F "#{@dirPrograms}/context-query.tmux.conf";
bind S source-file -F "#{@dirPrograms}/ssh.tmux.conf";
bind X source-file -F "#{@dirPrograms}/debug-menu.tmux.conf";
