set-option -g default-terminal "$TERM"
set-option -ag terminal-overrides "$TERM:RGB"

set-option -g focus-events on

set-option -g base-index 1

set-option editor nvim

set-option -w -g mode-keys vi
set-option -w -g pane-border-indicators arrows

set-option -g status-left-length 64
