# vars
set-option -sF @dirProjects "~/projects"
set-option -sF @cmdAgent "copilot"
set-option -sF @agentContextLines "10"

# global vars
set-option -sF @dirTtmux "#{d:current_file}"
set-option -sF @dirPrograms "#{@dirTtmux}/programs"

source-file -F "#{@dirTtmux}/init.tmux.conf"
source-file -F "#{@dirTtmux}/bindings.tmux.conf"
source-file -F "#{@dirTtmux}/options.tmux.conf"

display-message "ttmux initialized"
