set-option -F @agentSessionName "agent@#{session_name}"

# capture range around cursor
set-option -F @agentPromptStart "#{e|-:#{cursor_y},#{@agentContextLines}}"
set-option -F @agentPromptEnd "#{e|+:#{cursor_y},#{@agentContextLines}}"

# command to capture pane content, clean it, and load into tmux paste buffer
set-option -F @cmdLoadContext \
"tmux capture-pane -peCN -t \"#{pane_id}\" -S #{@agentPromptStart} -E #{@agentPromptEnd} | \"#{@dirTtmux}/scripts/clean-context\" --cursor-col #{cursor_x} | tmux load-buffer -"

# command to create or attach to agent session
set-option -F @commandAgentSession \
"tmux new-session -A -s \"#{@agentSessionName}\" \"#{@cmdAgent}\""

# main
run-shell "#{@cmdLoadContext}"
run-shell "tmux new-session -dA -s \"#{@agentSessionName}\" \"#{@cmdAgent}\""
run-shell "tmux paste-buffer -pt \"#{@agentSessionName}\""
run-shell "tmux display-popup -E '#{@commandAgentSession}'"
