set-option -F @agentSessionName "agent@#{session_name}"

# command to create or attach to agent session
set-option -F @commandAgentSession \
"tmux new-session -A -s \"#{@agentSessionName}\" \"#{@cmdAgent}\"";

# toggle: close popup if inside agent session, open otherwise
if-shell -F "#{m:agent@*,#{session_name}}" {
    detach-client
} {
    run-shell "tmux display-popup -b rounded -w 80 -h 75% -E '#{@commandAgentSession}'"
}
