set-option -F @agentSessionName "agent@#{session_name}"
set-option -F @commandAgentSession \
"tmux new-session -A -s \"#{@agentSessionName}\" \"#{@cmdAgent}\""

if-shell -F "#{m:agent@*,#{session_name}}" {
    detach-client
} {
    run-shell "#{@dirTtmux}/scripts/agent-popup '#{@dirTtmux}'"
}
