# capture range around cursor
set-option -F @captureContextStart "#{e|-:#{cursor_y},#{@agentContextLines}}"
set-option -F @captureContextEnd "#{e|+:#{cursor_y},#{@agentContextLines}}"

# command to capture pane content to file
set-option -F @cmdCaptureToFile \
"tmux capture-pane -peCN -t \"#{pane_id}\" -S #{@captureContextStart} -E #{@captureContextEnd} > #{@dirRuntime}/captured-context && echo #{cursor_x} > #{@dirRuntime}/captured-cursor-col"

# main
run-shell "#{@cmdCaptureToFile}"
display-message "context saved to #{@dirRuntime}/captured-context"
