set-option -F @agentSessionName "agent@#{session_name}"

# command to create or attach to agent session
set-option -F @commandAgentSession \
"tmux new-session -A -s \"#{@agentSessionName}\" \"#{@cmdAgent}\""

# capture context, then open persistent agent popup
source-file -F "#{@dirPrograms}/context-capture.tmux.conf"
run-shell "tmux new-session -dA -s \"#{@agentSessionName}\" \"#{@cmdAgent}\""
run-shell "tmux display-popup -E '#{@commandAgentSession}'"
