# @bind prefix o
# @popup-table agent
# @popup-key o detach-client
#
# context-prompt with automatic reference paste

set-option -F @agentSessionName "agent@#{session_name}"
set-option -F @commandAgentSession \
"tmux new-session -A -s \"#{@agentSessionName}\" \"#{@cmdAgent}\""
set-option -F @contextRef "see #{@dirRuntime}/context (#{pane_current_path}) "

if-shell -F "#{m:agent@*,#{session_name}}" {
    detach-client
} {
    source-file -F "#{@dirPrograms}/context-capture.tmux.conf"
    run-shell "tmux has-session -t \"#{@agentSessionName}\" 2>/dev/null || tmux new-session -d -s \"#{@agentSessionName}\" \"#{@cmdAgent}\""
    run-shell "tmux send-keys -l -t \"#{@agentSessionName}\" '#{@contextRef}'"
    run-shell "#{@dirTtmux}/scripts/agent-popup '#{@dirTtmux}'"
}
