# @bind prefix O
# @popup-table agent
# @popup-key O detach-client

set-option -F @agentSessionName "agent@#{session_name}"
set-option -F @commandAgentSession \
"tmux new-session -A -s \"#{@agentSessionName}\" \"#{@cmdAgent}\""

if-shell -F "#{m:agent@*,#{session_name}}" {
    detach-client
} {
    source-file -F "#{@dirPrograms}/context-capture.tmux.conf"
    run-shell "#{@dirTtmux}/scripts/agent-popup '#{@dirTtmux}' agent agent -w 80 -h 75%"
}
