# command to capture raw pane content
set-option -F @cmdCaptureRaw \
"tmux capture-pane -pe -t \"#{pane_id}\" > /tmp/ttmux-context-raw"

# command to clean captured content and prepend metadata
set-option -F @cmdCaptureClean \
"printf 'session: #{session_name}\npath: #{pane_current_path}\n---\n' > /tmp/ttmux-context && \
\"#{@dirTtmux}/scripts/clean-context\" --cursor-col #{cursor_x} < /tmp/ttmux-context-raw >> /tmp/ttmux-context"

# main
run-shell "#{@cmdCaptureRaw}"
run-shell "#{@cmdCaptureClean}"
