# toggle trace mode
if-shell -F "#{@debugTrace}" {
    set-option -s @debugTrace ""
    display-message "ttmux: trace OFF"
} {
    set-option -s @debugTrace "1"
    run-shell "echo '=== TRACE SESSION STARTED '$(date '+%H:%M:%S')' ===' > #{@dirRuntime}/debug.log"
    display-message "ttmux: trace ON -> #{@dirRuntime}/debug.log"
}
