# command to dump ttmux state to log
set-option -F @cmdDebugDumpVars \
"echo '--- TTMUX STATE DUMP ---' >> #{@dirRuntime}/debug.log && \
echo 'time: '$(date '+%H:%M:%S') >> #{@dirRuntime}/debug.log && \
echo 'session: #{session_name}' >> #{@dirRuntime}/debug.log && \
echo 'window: #{window_name}' >> #{@dirRuntime}/debug.log && \
echo 'pane: #{pane_id}' >> #{@dirRuntime}/debug.log && \
echo '' >> #{@dirRuntime}/debug.log && \
echo '-- server options --' >> #{@dirRuntime}/debug.log && \
tmux show-options -s | grep '^@' >> #{@dirRuntime}/debug.log && \
echo '' >> #{@dirRuntime}/debug.log && \
echo '-- session options --' >> #{@dirRuntime}/debug.log && \
tmux show-options | grep '^@' >> #{@dirRuntime}/debug.log && \
echo '' >> #{@dirRuntime}/debug.log"

# main
run-shell "#{@cmdDebugDumpVars}"
display-message "ttmux: state dumped to #{@dirRuntime}/debug.log"
