# @bind prefix X
#
# debug menu
display-menu -T "ttmux debug" \
"Dump vars" v "source-file -F \"#{@dirPrograms}/debug-vars.tmux.conf\"" \
"Toggle trace" t "source-file -F \"#{@dirPrograms}/debug-trace.tmux.conf\"" \
"Expand format" e "source-file -F \"#{@dirPrograms}/debug-expand.tmux.conf\"" \
"View log" l "split-window \"less +G #{@dirRuntime}/debug.log\""
