# @bind copy-mode-vi E
# @bind-action send-keys -X copy-pipe-and-cancel "cat > ${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}}/ttmux/edit-selection && tmux split-window -h 'nvim ${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}}/ttmux/edit-selection'"
