# @bind prefix P

set-option -F @cmdProjectList \
"ls #{@dirProjects}";

set-option -F @cmdProjectFzf \
"--tmux --border --border-label=\"projects\" --preview=\"ls #{@dirProjects}/{}\"";

set-option -F @cmdProjectLaunch \
"tmux set-option @projectLaunchProject \"{}\" && tmux source-file \"#{@dirPrograms}/project-launch.tmux.conf\"";

run-shell "#{@dirTtmux}/scripts/fzf-dispatch cmdProjectList cmdProjectFzf cmdProjectLaunch"
