set-option -F @projectLaunchSessionName "projects/#{@projectLaunchProject}"
set-option -F @projectLaunchSessionRoot "#{@dirProjects}/#{@projectLaunchProject}"

run-shell "#{@dirTtmux}/scripts/session-launch \
  '#{@projectLaunchSessionName}' \
  '#{@projectLaunchSessionRoot}'"
