# command to list projects
set-option -F @cmdProjectList \
"ls #{@dirProjects}";

# command to preview project dir in fzf
set-option -F @cmdProjectPreview \
"ls #{@dirProjects}/{}";

# command to select project
set-option -F @cmdProjectSelect \
"fzf --tmux --border --border-label=\"projects\" --preview=\"#{@cmdProjectPreview}\"";

# command to launch project
set-option -F @cmdProjectLaunch \
"tmux set-option @projectLaunchProject \"{}\" && tmux source-file \"#{@dirPrograms}/project-launch.tmux.conf\"";

# main
run-shell "#{@cmdProjectList} | #{@cmdProjectSelect} | xargs -I {} sh -c '#{@cmdProjectLaunch}'";
