set-option -F @projectLaunchSessionName "projects/#{@projectLaunchProject}"
set-option -F @projectLaunchSessionRoot "#{@dirProjects}/#{@projectLaunchProject}"

# command to initialize session for project
set-option -F @commandInitProjectSession \
"tmux new-window -S -n nvim \\\"nvim .\\\" && tmux split-window -v -l 20 && tmux select-pane -U -t nvim";

# command to launch session for project
set-option -F @commandCreateProjectSession \
"tmux new-session -dA -c \"#{@projectLaunchSessionRoot}\" -s \"#{@projectLaunchSessionName}\" \"#{@commandInitProjectSession}\"";

# main
if-shell "! tmux has-session -t #{@projectLaunchSessionName}" {
    run-shell "#{@commandCreateProjectSession}";
}

run-shell "tmux switch-client -t \"#{@projectLaunchSessionName}\"";
