# @bind prefix N
#
# main
command-prompt -p "project name:" \
"run-shell \"mkdir -p '#{@dirProjects}/%1' && tmux set-option @projectLaunchProject '%1' && tmux source-file '#{@dirPrograms}/project-launch.tmux.conf'\""
