set-option -F @projectLaunchSessionName "projects/#{@projectLaunchProject}"
set-option -F @projectLaunchSessionRoot "#{@dirProjects}/#{@projectLaunchProject}"

# command to launch session for project
set-option -F @commandCreateProjectSession \
"tmux new-session -dA -c \"#{@projectLaunchSessionRoot}\" -s \"#{@projectLaunchSessionName}\"";

# main
if-shell "! tmux has-session -t #{@projectLaunchSessionName}" {
    run-shell "#{@commandCreateProjectSession}";
}

run-shell "tmux switch-client -t \"#{@projectLaunchSessionName}\"";
