set-option -F @sshLaunchSessionName "ssh/#{@sshLaunchHost}"

# command to create ssh session
set-option -F @commandCreateSshSession \
"tmux new-session -dA -s \"#{@sshLaunchSessionName}\" \"ssh #{@sshLaunchHost}\"";

# main
if-shell "! tmux has-session -t #{@sshLaunchSessionName}" {
    run-shell "#{@commandCreateSshSession}";
}

run-shell "tmux switch-client -t \"#{@sshLaunchSessionName}\"";
