# @bind prefix H
#
# command to list ssh hosts from config
set-option -F @cmdSshList \
"awk '/^Host / && !/\\*/ { print $2 }' ~/.ssh/config";

# command to select host
set-option -F @cmdSshSelect \
"fzf --tmux --border --border-label=\"ssh\"";

# command to launch ssh session
set-option -F @cmdSshLaunch \
"tmux set-option @sshLaunchHost \"{}\" && tmux source-file \"#{@dirPrograms}/ssh-launch.tmux.conf\"";

# main
run-shell "#{@cmdSshList} | #{@cmdSshSelect} | xargs -I {} #{@cmdSshLaunch}";
