# @bind prefix H

set-option -F @cmdSshList \
"awk '/^Host / && !/\\*/ { print $2 }' $HOME/.ssh/config";

set-option -F @cmdSshFzf \
"--tmux --border --border-label=\"ssh\"";

set-option -F @cmdSshLaunch \
"tmux set-option @sshLaunchHost \"{}\" && tmux source-file \"#{@dirPrograms}/ssh-launch.tmux.conf\"";

run-shell "#{@dirTtmux}/scripts/fzf-dispatch cmdSshList cmdSshFzf cmdSshLaunch"
