# @bind prefix T
#
# telescope: search across multiple sources with preview

set-option -F @cmdTelescope "#{@dirTtmux}/scripts/telescope"

run-shell "url=$(#{@cmdTelescope}) && [ -n \"\$url\" ] && tmux display-popup -b rounded -w 90% -h 80% -E \"w3m \$url\" || true"
